-- CRIANDO TABELA PARA ARMAZENAR DADOS DE CLIENTES:
CREATE TABLE cliente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL
);

-- CRIANDO TABELA PARA ARMAZENAR DADOS DE PRODUTOS:
CREATE TABLE produto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    valor DOUBLE NOT NULL
);

-- CRIANDO TABELA PARA ARMAZENAR DADOS DE PEDIDOS, SE JÁ NÃO EXISTIR:
CREATE TABLE IF NOT EXISTS pedido (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CRIANDO TABELA PARA ARMAZENAR OS ITEMS DE CADA PEDIDO:
CREATE TABLE pedido_item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quantidade INT NOT NULL,
    valor_total DOUBLE NOT NULL,
    pedido_id INT NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedido (id)
);

